(()=>{'use strict';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
let data=null,peaks=[],last=null;
const templates={
 ir:[{name:'Ir 化学态 1',kind:'doublet',center:61.8,cmin:60.5,cmax:63.2,width:1.15,wmin:.7,wmax:1.9,area:1,fitC:true,fitW:true,fitA:true,split:3.0,ratio:.75,lockSplit:true,lockRatio:true}],
 pb:[{name:'Pb 化学态 1',kind:'doublet',center:138.6,cmin:136.5,cmax:140.5,width:1.25,wmin:.8,wmax:2.0,area:1,fitC:true,fitW:true,fitA:true,split:4.86,ratio:.75,lockSplit:true,lockRatio:true}],
 o:[{name:'Lattice O',kind:'single',center:529.6,cmin:528.5,cmax:531,width:1.15,wmin:.7,wmax:1.9,area:1,fitC:true,fitW:true,fitA:true},{name:'OH / surface O',kind:'single',center:531.2,cmin:530,cmax:532.5,width:1.35,wmin:.8,wmax:2.2,area:.5,fitC:true,fitW:true,fitA:true}],
 custom:[{name:'组分 1',kind:'single',center:0,cmin:-1,cmax:1,width:1.2,wmin:.6,wmax:2.2,area:1,fitC:true,fitW:true,fitA:true}]
};
const clone=x=>JSON.parse(JSON.stringify(x));
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function parse(text){const rows=[];for(const line of text.split(/\r?\n/)){const v=line.trim().split(/[\s,;\t]+/).map(Number);if(v.length>=2&&Number.isFinite(v[0])&&Number.isFinite(v[1]))rows.push([v[0],v[1]])}if(rows.length<8)throw Error('未找到至少 8 行两列数值数据');rows.sort((a,b)=>a[0]-b[0]);const shift=(+$('targetRef').value||0)-(+($('measuredRef').value)||+($('targetRef').value)||0);const x=rows.map(r=>r[0]+shift),raw=rows.map(r=>r[1]),lo=Math.min(...raw),hi=Math.max(...raw),span=hi-lo||1;return{x,y:raw.map(v=>(v-lo)/span),raw,shift}}
function background(y,type){const n=y.length;if(type==='none')return Array(n).fill(0);if(type==='linear')return y.map((_,i)=>y[0]+(y[n-1]-y[0])*i/(n-1));if(type==='tougaard'){const out=Array(n).fill(0),dx=1/n,B=.25,C=.12;for(let i=0;i<n;i++){let s=0;for(let j=i+1;j<n;j++){const d=(j-i)/n;s+=(y[j]-Math.min(y[0],y[n-1]))*B*d/Math.pow(C+d*d,2)*dx}out[i]=Math.min(y[i],Math.max(0,Math.min(y[0],y[n-1])+.02*s))}return out}
 let b=y.map((_,i)=>y[0]+(y[n-1]-y[0])*i/(n-1));for(let k=0;k<40;k++){const q=y.map((v,i)=>Math.max(0,v-b[i])),cum=Array(n).fill(0);for(let i=n-2;i>=0;i--)cum[i]=cum[i+1]+(q[i]+q[i+1])/2;const total=cum[0]||1;b=b.map((_,i)=>y[n-1]+(y[0]-y[n-1])*cum[i]/total)}return b}
function pv(x,c,w,eta,asym=false){const ww=Math.max(.03,w*(asym&&x<c?1.32:1)),z=(x-c)/ww,g=Math.exp(-4*Math.log(2)*z*z),l=1/(1+4*z*z);return(1-eta)*g+eta*l}
function curves(pList,x){const eta=$('shape').value==='pv30'?.3:$('shape').value==='pv50'?.5:$('shape').value==='pv70'?.7:.45,asym=$('shape').value==='asym';return pList.map(p=>{const main=x.map(v=>p.area*pv(v,p.center,p.width,eta,asym));if(p.kind!=='doublet')return{name:p.name,y:main,secondary:null};const sec=x.map(v=>p.area*p.ratio*pv(v,p.center+p.split,p.width,eta,asym));return{name:p.name,y:main.map((v,i)=>v+sec[i]),secondary:p.center+p.split}})}
function evaluate(pList,bg){const cs=curves(pList,data.x),fit=bg.map((v,i)=>v+cs.reduce((s,c)=>s+c.y[i],0)),res=data.y.map((v,i)=>v-fit[i]),sse=res.reduce((s,v)=>s+v*v,0);return{cs,fit,res,sse}}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function optimize(){if(!data)throw Error('请先载入实验谱');syncRows();const bg=background(data.y,$('background').value);const maxY=Math.max(...data.y.map((v,i)=>Math.max(0,v-bg[i])));peaks.forEach(p=>{if(!Number.isFinite(p.area)||p.area<=0)p.area=maxY});let best=evaluate(peaks,bg),steps=peaks.map(p=>({c:Math.max(.03,(p.cmax-p.cmin)/8),w:Math.max(.02,(p.wmax-p.wmin)/8),a:Math.max(.01,p.area*.25)}));const rounds=clamp(+$('iterations').value||350,50,1500);for(let iter=0;iter<rounds;iter++){let improved=false;for(let j=0;j<peaks.length;j++){const p=peaks[j],spec=[['center','c','fitC',p.cmin,p.cmax],['width','w','fitW',p.wmin,p.wmax],['area','a','fitA',0,10]];for(const [key,sk,fk,min,max] of spec){if(!p[fk])continue;const old=p[key];for(const dir of [-1,1]){p[key]=clamp(old+dir*steps[j][sk],min,max);const trial=evaluate(peaks,bg);if(trial.sse+1e-12<best.sse){best=trial;improved=true;break}p[key]=old}}}if(!improved||iter%18===17)steps.forEach(s=>{s.c*=.62;s.w*=.62;s.a*=.62});if(Math.max(...steps.flatMap(s=>[s.c,s.w,s.a]))<1e-5)break}return{...best,bg}}
function peakRow(p,i){const dbl=p.kind==='doublet';return`<tr data-i="${i}"><td><input data-k="name" value="${esc(p.name)}"></td><td><select data-k="kind"><option value="single" ${!dbl?'selected':''}>单峰</option><option value="doublet" ${dbl?'selected':''}>双峰</option></select></td><td><input data-k="center" type="number" step=".01" value="${p.center}"></td><td><div class="range"><input data-k="cmin" type="number" step=".01" value="${p.cmin}"><input data-k="cmax" type="number" step=".01" value="${p.cmax}"></div></td><td><input data-k="width" type="number" step=".01" value="${p.width}"></td><td><div class="range"><input data-k="wmin" type="number" step=".01" value="${p.wmin}"><input data-k="wmax" type="number" step=".01" value="${p.wmax}"></div></td><td><input data-k="area" type="number" step=".01" min="0" value="${p.area}"></td><td><div class="checks"><label><input data-k="fitC" type="checkbox" ${p.fitC?'checked':''}>峰位</label><label><input data-k="fitW" type="checkbox" ${p.fitW?'checked':''}>FWHM</label><label><input data-k="fitA" type="checkbox" ${p.fitA?'checked':''}>面积</label></div></td><td>${dbl?`<label>Δ <input data-k="split" type="number" step=".01" value="${p.split}"></label><label>从/主 <input data-k="ratio" type="number" step=".01" value="${p.ratio}"></label><div class="checks"><label><input data-k="lockSplit" type="checkbox" ${p.lockSplit?'checked':''}>固定分裂</label><label><input data-k="lockRatio" type="checkbox" ${p.lockRatio?'checked':''}>固定比例</label></div>`:'—'}</td><td><button data-remove="${i}" class="secondary">删除</button></td></tr>`}
function renderRows(){ $('peakRows').innerHTML=peaks.map(peakRow).join('');validate() }
function syncRows(){[...$('peakRows').rows].forEach((tr,i)=>tr.querySelectorAll('[data-k]').forEach(el=>{const k=el.dataset.k;peaks[i][k]=el.type==='checkbox'?el.checked:el.type==='number'?+el.value:el.value}));validate()}
function validate(){const w=[];if(!data)w.push('尚未载入实验谱。');const tol=+$('widthTolerance').value||.25;peaks.forEach(p=>{if(p.cmin>=p.cmax)w.push(`${p.name}：峰位上下限无效。`);if(p.wmin<=0||p.wmin>=p.wmax)w.push(`${p.name}：FWHM 范围无效。`);if(p.width<.4||p.width>3)w.push(`${p.name}：FWHM ${p.width.toFixed(2)} eV 需核查仪器与样品依据。`);if(p.kind==='doublet'&&(!p.lockSplit||!p.lockRatio))w.push(`${p.name}：建议锁定双峰分裂和面积比。`)});if(peaks.length>1){const widths=peaks.map(p=>p.width);if(Math.max(...widths)-Math.min(...widths)>tol)w.push(`组分 FWHM 差异超过统一容许值 ±${tol} eV。`)}if(!w.length)w.push('当前参数边界与双峰约束通过基础检查；化学归属仍需外部证据。');$('warnings').innerHTML=w.map(x=>`<li>${esc(x)}</li>`).join('')}
function applyTemplate(){const key=$('region').value;peaks=clone(templates[key]);if(data){const x0=Math.min(...data.x),x1=Math.max(...data.x),mid=(x0+x1)/2,span=x1-x0;peaks.forEach((p,i)=>{if(p.center<x0||p.center>x1){p.center=mid+(i-(peaks.length-1)/2)*Math.min(1.5,span/6);p.cmin=Math.max(x0,p.center-1);p.cmax=Math.min(x1,p.center+1)}})}renderRows();last=null;draw()}
function metrics(result){const n=data.y.length,k=peaks.length*3,mean=data.y.reduce((a,b)=>a+b,0)/n,sst=data.y.reduce((s,v)=>s+(v-mean)**2,0),r2=1-result.sse/(sst||1),rmse=Math.sqrt(result.sse/n),red=result.sse/Math.max(1,n-k),bias=result.res.reduce((a,b)=>a+b,0)/n;return{r2,rmse,red,bias}}
function runFit(){try{last=optimize();renderRows();const m=metrics(last);$('metrics').innerHTML=[['R²',m.r2.toFixed(6)],['Reduced χ²',m.red.toExponential(3)],['RMSE',m.rmse.toExponential(3)],['残差偏置',m.bias.toExponential(3)]].map(v=>`<article><b>${v[0]}</b><span>${v[1]}</span></article>`).join('');const areas=peaks.map(p=>p.area*(p.kind==='doublet'?1+p.ratio:1)),total=areas.reduce((a,b)=>a+b,0)||1;$('resultRows').innerHTML=peaks.map((p,i)=>`<tr><td>${esc(p.name)}</td><td>${p.center.toFixed(3)} eV</td><td>${p.width.toFixed(3)} eV</td><td>${areas[i].toFixed(4)}</td><td>${(100*areas[i]/total).toFixed(2)}%</td><td>${p.kind==='doublet'?(p.center+p.split).toFixed(3)+' eV；比例 '+p.ratio.toFixed(3):'—'}</td><td>${p.kind==='doublet'&&p.lockSplit&&p.lockRatio?'双峰锁定':'边界约束'}</td></tr>`).join('');$('fitBadge').textContent=`拟合完成 · R² ${m.r2.toFixed(4)}`;$('message').textContent='拟合完成。请结合随机残差、参数边界和独立化学证据判断结果。';draw()}catch(e){$('message').textContent=e.message;$('fitBadge').textContent='需要检查输入'}}
function svgEl(tag,attrs={}){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
function draw(){const svg=$('chart');svg.innerHTML='';if(!data){const t=svgEl('text',{x:600,y:300,'text-anchor':'middle',fill:'#9bc9cf','font-size':22});t.textContent='载入谱图后显示拟合曲线';svg.append(t);return}const bg=last?.bg||background(data.y,$('background').value),ev=last||evaluate(peaks,bg),x=data.x,y=data.y,W=1200,L=75,R=25,T=35,H=420,B=95,RH=100,x0=Math.min(...x),x1=Math.max(...x),xp=v=>L+(x1-v)/(x1-x0)*(W-L-R),yp=v=>T+(1-v)*H,rp=v=>T+H+B+RH/2-v/(Math.max(...ev.res.map(Math.abs))||1)*RH*.43;svg.append(svgEl('rect',{x:L,y:T,width:W-L-R,height:H,fill:'#061820',stroke:'#245662'}),svgEl('rect',{x:L,y:T+H+B,width:W-L-R,height:RH,fill:'#061820',stroke:'#245662'}));const path=(ys,color,width=2,map=yp,dash='')=>{const d=ys.map((v,i)=>(i?'L':'M')+xp(x[i]).toFixed(1)+' '+map(v).toFixed(1)).join(' '),p=svgEl('path',{d,fill:'none',stroke:color,'stroke-width':width});if(dash)p.setAttribute('stroke-dasharray',dash);svg.append(p)};path(y,'#e8ffff',2);path(ev.fit,'#ffb35c',3);path(bg,'#65aeb8',1.5,yp,'7 5');const colors=['#41efc4','#db77ff','#6da8ff','#ff6687','#ffe266','#74df85'];ev.cs.forEach((c,i)=>path(c.y.map((v,j)=>v+bg[j]),colors[i%colors.length],1.3));path(ev.res,'#5be1df',1.5,rp);svg.append(svgEl('line',{x1:L,y1:rp(0),x2:W-R,y2:rp(0),stroke:'#32616b','stroke-dasharray':'5 5'}));[['实验','#e8ffff'],['总拟合','#ffb35c'],['背景','#65aeb8'],['残差','#5be1df']].forEach((a,i)=>{const t=svgEl('text',{x:L+i*105,y:20,fill:a[1],'font-size':14});t.textContent=a[0];svg.append(t)});for(let i=0;i<=5;i++){const v=x1-(x1-x0)*i/5,t=svgEl('text',{x:L+(W-L-R)*i/5,y:T+H+25,'text-anchor':'middle',fill:'#a9cdd1','font-size':13});t.textContent=v.toFixed(1);svg.append(t)}const lab=svgEl('text',{x:W/2,y:T+H+48,'text-anchor':'middle',fill:'#a9cdd1','font-size':14});lab.textContent='Binding energy (eV) · 高结合能在左';svg.append(lab)}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportCurve(){if(!last)return;const lines=['binding_energy,experimental,background,fit,residual',...data.x.map((v,i)=>[v,data.y[i],last.bg[i],last.fit[i],last.res[i]].join(','))];download('xps_fit_curves.csv',lines.join('\n'),'text/csv')}
function exportParams(){if(!last)return;const total=peaks.reduce((s,p)=>s+p.area*(p.kind==='doublet'?1+p.ratio:1),0);download('xps_fit_parameters.csv',['component,mode,center_eV,fwhm_eV,total_area,area_percent,splitting_eV,secondary_ratio',...peaks.map(p=>[p.name,p.kind,p.center,p.width,p.area*(p.kind==='doublet'?1+p.ratio:1),100*p.area*(p.kind==='doublet'?1+p.ratio:1)/total,p.split||'',p.ratio||''].join(','))].join('\n'),'text/csv')}
function demo(){const x=[],y=[];for(let i=0;i<=350;i++){const e=58+i*.03,n=(Math.sin(i*12.9898)*43758.5453)%1;x.push(e);y.push(.09+.006*i/350+1.0*pv(e,61.75,1.08,.3)+.75*pv(e,64.75,1.08,.3)+.42*pv(e,62.75,1.22,.3)+.315*pv(e,65.75,1.22,.3)+.012*(n-Math.floor(n)))}data={x,y,raw:y,shift:0};peaks=clone(templates.ir);peaks.push({...clone(templates.ir[0]),name:'Ir 化学态 2',center:62.7,cmin:61.8,cmax:64,area:.35});$('region').value='ir';renderRows();draw();$('message').textContent='已载入合成 Ir 4f 演示谱，仅用于操作练习，不作为参考峰位数据库。'}
$('file').onchange=async e=>{try{data=parse(await e.target.files[0].text());applyTemplate();$('message').textContent=`已载入 ${data.x.length} 点；能量平移 ${data.shift.toFixed(3)} eV。`;$('fitBadge').textContent='数据已载入';draw()}catch(err){$('message').textContent=err.message}};
$('applyTemplate').onclick=applyTemplate;$('loadDemo').onclick=demo;$('fit').onclick=runFit;$('addPeak').onclick=()=>{const x=data?data.x:[0,2],mid=(x[0]+x[x.length-1])/2;peaks.push({name:`组分 ${peaks.length+1}`,kind:'single',center:mid,cmin:mid-1,cmax:mid+1,width:1.2,wmin:.7,wmax:2,area:.3,fitC:true,fitW:true,fitA:true});renderRows()};$('peakRows').onclick=e=>{if(e.target.dataset.remove!==undefined){syncRows();peaks.splice(+e.target.dataset.remove,1);renderRows()}};$('peakRows').onchange=syncRows;$('widthTolerance').onchange=validate;$('background').onchange=draw;$('shape').onchange=draw;$('downloadCurve').onclick=exportCurve;$('downloadCsv').onclick=exportParams;$('downloadJson').onclick=()=>last&&download('xps_fit_result.json',JSON.stringify({metadata:{region:$('region').value,background:$('background').value,shape:$('shape').value,energy_shift:data.shift},peaks,metrics:metrics(last),curves:{energy:data.x,experimental:data.y,background:last.bg,fit:last.fit,residual:last.res}},null,2),'application/json');$('downloadSvg').onclick=()=>download('xps_fit.svg',new XMLSerializer().serializeToString($('chart')),'image/svg+xml');$('region').onchange=applyTemplate;
applyTemplate();draw();
})();
